Allow to skip the generation of EE definition
redhat-cop/ee_utilities pull request #154
Opened 2024-05-02 19:34 UTC by Spredzy

# What does this PR do?

Allow a user to skip the generation of EE definition and provide a definition before hand for this role to call builder.

# How should this be tested?

Specifing `skip_generation` to an item of `ee_list`

# Is there a relevant Issue open for this?

N/A

# Other Relevant info, PRs, etc

N/A

2024-05-02 20:32 UTC, djdanielsson requested changes

2024-05-02 20:32 UTC, djdanielsson commented on roles/ee_builder/README.md
> +|`skip_generation`|bool|false|Should the generation of execution_environment.yml be skipped and an already provided definition be built.|
wouldn't it be `Should the generation of execution_environment.yml be skipped and an already provided definition be used.` ?

2024-06-18 14:55 UTC, djdanielsson commented on roles/ee_builder/README.md
> +|`skip_generation`|bool|false|Should the generation of execution_environment.yml be skipped and an already provided definition be built.|
@Spredzy if you update this then we can get this merged, looking to do a release soon and would like to include your changes

2024-06-18 15:21 UTC, sean-m-sullivan approved these changes

2024-06-18 15:46 UTC, merged