allows for publishing collections to AAP 2.5 hub
redhat-cop/ee_utilities pull request #174
Opened 2024-11-14 18:39 UTC by djdanielsson

# What does this PR do?

Brief explanation of the code or documentation change you've made
allows for publishing collections to AAP 2.5 hub
# How should this be tested?

manual
# Is there a relevant Issue open for this?

Provide a link to any open issues that describe the problem you are solving.
resolves #173 

# Other Relevant info, PRs, etc

none

2024-12-05 14:17 UTC, Tompage1994 requested changes

2024-12-05 14:17 UTC, Tompage1994 commented on roles/ee_builder/templates/ansible.cfg.j2
> +url=https://{{ ee_ah_host }}{% if ee_aap_version == 2.5 %}/pulp_ansible/galaxy/rh-certified/{% else %}/api/galaxy/content/rh-certified/{% endif %}
Should these be `ee_aap_version >= 2.5`?

2025-01-23 17:15 UTC, djdanielsson commented
@Tompage1994 good now?

2025-01-24 09:44 UTC, Tompage1994 approved these changes

2025-01-24 09:44 UTC, merged